buildscript {
    repositories {
        mavenCentral()

        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }

        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }

        maven {
            name = "jitpack"
            url = "https://jitpack.io"
        }
    }

    dependencies {
        classpath 'com.github.GTNewHorizons:ForgeGradle:1.2.11'
    }
}

apply plugin: 'forge'

version = "0.3.0-gtnh"
group = "com.mikuliku.touhoulittlemaidgtnh"
archivesBaseName = "TouhouLittleMaid-GTNH"

sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "run"
    mappings = "stable_12"
}

repositories {
    mavenCentral()

    maven {
        name = "forge"
        url = "https://maven.minecraftforge.net/"
    }

    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/repositories/snapshots/"
    }

    maven {
        name = "jitpack"
        url = "https://jitpack.io"
    }

    maven {
        name = "GTNH"
        url = "https://nexus.gtnewhorizons.com/repository/public/"
    }
}

dependencies {
    compileOnly 'com.github.GTNewHorizons:GT5-Unofficial:5.09.52.594:dev'
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include '**/*.info'
        expand(
                'version': project.version,
                'mcversion': project.minecraft.version
        )
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude '**/*.info'
    }
}

jar {
    manifest {
        attributes(
                'FMLCorePluginContainsFMLMod': 'true'
        )
    }
}
